#!/usr/bin/env node
/**
 * build-plugins — render this repo's plugin manifests from `plugin.source.json`.
 *
 * Claude Code, Cursor, Codex, and GitHub Copilot all read the same payload (`skills/`),
 * but each wants its own manifest, in its own directory, with its own way of binding
 * credentials into an MCP config. Those manifests are small enough to hand-write and
 * different enough that hand-writing them drifts. So: one source of truth here, four
 * generated manifest sets, and a --check mode CI runs to prove nobody edited the output.
 *
 * Usage:
 *   node scripts/build-plugins.mjs            # write
 *   node scripts/build-plugins.mjs --check    # exit 1 if any output is stale
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const GENERATED_NOTE =
  'Generated by scripts/build-plugins.mjs from plugin.source.json. Do not edit by hand.';

// The manifests carry no provenance marker of their own: `claude plugin validate` warns on
// any field it does not recognise, and a comment key is exactly that. Provenance lives in
// generated/README.md, .gitattributes, and CONTRIBUTING instead.

// ---------------------------------------------------------------------------
// args
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);
if (args.includes('--help') || args.includes('-h')) {
  console.log(`build-plugins — render plugin manifests from plugin.source.json

  --check    verify the committed output matches what would be generated (CI gate)
  --help     show this message
`);
  process.exit(0);
}
const checkOnly = args.includes('--check');

// ---------------------------------------------------------------------------
// inputs
// ---------------------------------------------------------------------------

const source = JSON.parse(readFileSync(join(repoRoot, 'plugin.source.json'), 'utf8'));

// A logo path that points at nothing fails silently in both clients that read it — Cursor
// serves a 404 and Codex logs a warning nobody sees. Catch it here instead.
if (source.logo && !existsSync(join(repoRoot, source.logo))) {
  throw new Error(`plugin.source.json declares logo "${source.logo}", which does not exist.`);
}

/** Identity fields shared by every vendor's manifest. */
const identity = {
  name: source.name,
  displayName: source.displayName,
  description: source.description,
  author: source.author,
  homepage: source.homepage,
  repository: source.repository,
  license: source.license,
  keywords: source.keywords,
};

/**
 * Agent Plugins v1 closes the manifest schema (§5.2): the only permitted top-level fields
 * are `$schema`, `name`, `version`, `description`, `author`, `homepage`, `repository`,
 * `license`, `keywords`, and `extensions`. `displayName` is not among them, so the portable
 * manifest carries identity minus that one field.
 */
const { displayName: _displayName, ...portableIdentity } = identity;

/**
 * Credential binding differs per agent:
 *   Claude — `${user_config.<key>}`, prompted at enable time, secrets to the keychain
 *   others — `${ENV_VAR}`, expanded from the environment
 * Everything else about the MCP config is identical, so build it once per style.
 */
function mcpConfig(style) {
  const { credentials, urlTemplate, headers, serverName, type } = source.mcp;
  const ref = (key) =>
    style === 'claude'
      ? `\${user_config.${credentials[key].env.toLowerCase()}}`
      : `\${${credentials[key].env}}`;

  const substitute = (template) => template.replace(/\{(\w+)\}/g, (_, key) => ref(key));

  return {
    mcpServers: {
      [serverName]: {
        type,
        url: substitute(urlTemplate),
        headers: Object.fromEntries(
          Object.entries(headers).map(([header, template]) => [header, substitute(template)])
        ),
      },
    },
  };
}

/** Claude's enable-time prompt, derived from the same credential definitions. */
function userConfig() {
  return Object.fromEntries(
    Object.values(source.mcp.credentials).map((credential) => [
      credential.env.toLowerCase(),
      {
        type: 'string',
        title: credential.title,
        description: credential.description,
        ...(credential.required ? { required: true } : {}),
        ...(credential.sensitive ? { sensitive: true } : {}),
        ...(credential.default ? { default: credential.default } : {}),
      },
    ])
  );
}

function marketplace() {
  return {
    name: source.marketplace.name,
    description: source.marketplace.description,
    owner: source.marketplace.owner,
    plugins: [
      {
        name: source.name,
        source: './',
        description: source.description,
      },
    ],
  };
}

// ---------------------------------------------------------------------------
// README skill inventory
// ---------------------------------------------------------------------------

/** Minimal frontmatter reader — enough for `name` and `description`, no YAML dep. */
function skillFrontmatter(skillPath) {
  const raw = readFileSync(skillPath, 'utf8');
  const match = raw.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return null;

  const fields = {};
  let currentKey = null;
  for (const line of match[1].split('\n')) {
    const keyed = line.match(/^(\w[\w-]*):\s?(.*)$/);
    if (keyed) {
      currentKey = keyed[1];
      // `description: >-` folds onto the following indented lines.
      fields[currentKey] = keyed[2].trim() === '>-' ? '' : keyed[2].trim();
    } else if (currentKey && /^\s+\S/.test(line)) {
      fields[currentKey] = `${fields[currentKey] ? `${fields[currentKey]} ` : ''}${line.trim()}`;
    } else if (!/^\s/.test(line)) {
      currentKey = null;
    }
  }
  return fields;
}

/**
 * A skill `description` is trigger text written for the model, so it is long and often
 * one enormous sentence. Take the first sentence, then clip at a word boundary — a table
 * row that wraps five times is worse than one that ends in an ellipsis.
 */
function summarize(description, limit = 180) {
  const firstSentence = description.replace(/\s+/g, ' ').trim().split(/(?<=\.)\s/)[0];
  if (firstSentence.length <= limit) return firstSentence;

  const clipped = firstSentence.slice(0, limit);
  return `${clipped.slice(0, clipped.lastIndexOf(' ')).replace(/[,;:—-]$/, '')}…`;
}

function skillInventoryTable() {
  const skillsDir = join(repoRoot, 'skills');
  const rows = readdirSync(skillsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && existsSync(join(skillsDir, entry.name, 'SKILL.md')))
    .map((entry) => entry.name)
    .sort()
    .map((name) => {
      const fields = skillFrontmatter(join(skillsDir, name, 'SKILL.md')) ?? {};
      return `| \`${name}\` | ${summarize(fields.description ?? '')} |`;
    });

  return ['| Skill | What it covers |', '| --- | --- |', ...rows].join('\n');
}

/** Replace the region between the inventory markers in README.md, leaving prose alone. */
function readmeWithInventory() {
  const readmePath = join(repoRoot, 'README.md');
  const readme = readFileSync(readmePath, 'utf8');
  const start = '<!-- begin:skill-inventory -->';
  const end = '<!-- end:skill-inventory -->';

  if (!readme.includes(start) || !readme.includes(end)) {
    throw new Error(
      `README.md is missing the ${start} / ${end} markers that fence the generated skill table.`
    );
  }

  const pattern = new RegExp(`${start}[\\s\\S]*?${end}`);
  return readme.replace(
    pattern,
    `${start}\n<!-- ${GENERATED_NOTE} -->\n\n${skillInventoryTable()}\n\n${end}`
  );
}

// ---------------------------------------------------------------------------
// outputs
// ---------------------------------------------------------------------------

const json = (value) => `${JSON.stringify(value, null, 2)}\n`;

const outputs = [
  // Claude Code. Two things here are empirical, not stylistic — verified against
  // Claude Code 2.1.220 with `claude plugin details`:
  //
  //   `skills` is intentionally unset: for Claude the manifest key *adds to* the default
  //   skills/ scan rather than replacing it, so declaring it double-loads.
  //
  //   The MCP config must live at `.mcp.json` in the plugin root. Both documented
  //   alternatives — an `mcpServers` path in the manifest and an inline `mcpServers`
  //   object — are silently ignored: the plugin installs fine and reports "MCP servers
  //   (0)". Because the plugin root is the repo root, this file is also the project-scope
  //   MCP config for anyone working in this repo; see CONTRIBUTING.
  {
    path: '.claude-plugin/plugin.json',
    content: json({
      $schema: 'https://json.schemastore.org/claude-code-plugin-manifest.json',
      ...identity,
      userConfig: userConfig(),
    }),
  },
  { path: '.claude-plugin/marketplace.json', content: json(marketplace()) },
  { path: '.mcp.json', content: json(mcpConfig('claude')) },

  // Cursor. Skills auto-discover from skills/; `logo` is a bare repo-relative path, which
  // Cursor resolves to a raw.githubusercontent.com URL at the installed commit SHA.
  {
    path: '.cursor-plugin/plugin.json',
    content: json({
      ...identity,
      logo: source.logo,
      mcp: './generated/cursor/mcp.json',
    }),
  },
  { path: '.cursor-plugin/marketplace.json', content: json(marketplace()) },
  { path: 'generated/cursor/mcp.json', content: json(mcpConfig('env')) },

  // Codex. Declares skills explicitly per the Codex packaging guide; the marketplace
  // lives at .agents/plugins/ so the repo doubles as a Codex repo-marketplace.
  {
    path: '.codex-plugin/plugin.json',
    content: json({
      ...identity,
      skills: './skills/',
      mcpServers: './generated/codex/mcp.json',
      // Codex reads presentation metadata from `interface`, and resolves its asset paths
      // locally inside the installed package rather than over the network. Paths must
      // start with `./`; Codex warns and ignores them otherwise.
      interface: { logo: `./${source.logo}` },
    }),
  },
  { path: '.agents/plugins/marketplace.json', content: json(marketplace()) },
  { path: 'generated/codex/mcp.json', content: json(mcpConfig('env')) },

  // GitHub Copilot, via the portable Agent Plugins v1 manifest at the repo root. Copilot
  // reads `plugin.json` there and discovers skills from `skills/<name>/SKILL.md`, which is
  // the layout this repo already uses — so the manifest is the whole integration.
  //
  // `version` stays omitted for the same reason as everywhere else (Claude's SHA fallback);
  // the spec makes it optional, so leaving it out is still conformant.
  //
  // Deliberately no root `mcp.json`. §7.2.1 forbids placeholder and environment-variable
  // expansion in header values AND forbids embedding credentials, while our server needs an
  // `x-api-key` header plus the project ID in the URL path and does not support OAuth. A
  // conformant `mcp.json` therefore could not authenticate, and a non-conformant one would
  // send the literal `${UNIFORM_API_KEY}` as the header — failing confusingly instead of
  // loudly. Copilot users configure the MCP server themselves; skills are what ship here.
  {
    path: 'plugin.json',
    content: json({
      $schema: 'https://agent-plugins.org/schemas/1.0.0/plugin.schema.json',
      ...portableIdentity,
    }),
  },

  { path: 'README.md', content: readmeWithInventory() },

  // The manifests can't say this about themselves without tripping schema validation.
  {
    path: 'generated/README.md',
    content: `# Generated plugin output

${GENERATED_NOTE}

Everything in this directory, plus the root \`plugin.json\` and the \`.claude-plugin/\`,
\`.cursor-plugin/\`, \`.codex-plugin/\`, and \`.agents/plugins/\` manifests, is build output.
Edit \`plugin.source.json\` and run:

\`\`\`bash
npm run build:plugins
\`\`\`

\`npm run validate:plugins\` fails if any of it drifts, and CI runs that on every PR.
`,
  },
];

// ---------------------------------------------------------------------------
// write / check
// ---------------------------------------------------------------------------

/**
 * Stale files in generated/ are as much a drift bug as changed ones — a skill renamed in
 * skills/ would otherwise leave its old twin behind and agents would keep loading it.
 */
function orphanedGeneratedFiles() {
  const expected = new Set(outputs.map((output) => output.path));
  const found = [];

  const walk = (dir) => {
    if (!existsSync(dir)) return;
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else {
        const rel = relative(repoRoot, full);
        if (!expected.has(rel)) found.push(rel);
      }
    }
  };
  walk(join(repoRoot, 'generated'));
  return found;
}

const stale = [];
for (const { path, content } of outputs) {
  const full = join(repoRoot, path);
  const current = existsSync(full) && statSync(full).isFile() ? readFileSync(full, 'utf8') : null;
  if (current === content) continue;

  if (checkOnly) {
    stale.push(current === null ? `${path} (missing)` : path);
  } else {
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, content);
  }
}

const orphans = orphanedGeneratedFiles();
if (checkOnly) {
  const problems = [...stale, ...orphans.map((path) => `${path} (orphaned)`)];
  if (problems.length > 0) {
    console.error('Generated plugin files are out of date:\n');
    for (const problem of problems) console.error(`  ${problem}`);
    console.error('\nRun `npm run build:plugins` and commit the result.');
    process.exit(1);
  }
  console.log(`All ${outputs.length} generated plugin files are up to date.`);
} else {
  for (const path of orphans) rmSync(join(repoRoot, path));
  console.log(
    `Wrote ${outputs.length} plugin files${orphans.length ? `, removed ${orphans.length} orphaned` : ''}.`
  );
}
